### ISSUE TITLE
non agent api beta 

### ISSUE THREAD

**Issue by juanykty** [masterfermin02/ViciMobManager#1]
in the line 56 on the file "CampaignActivity" I need the file non_agent_api_beta.php but in my server I only have non_agent_api.php and the function get_campaign dont exist on my code can you send me the file 
non_agent_api_beta.php?

`        String url = "http://"+config.getVicidialUrl()+"/"+config.getVicidialFolder()+"/non_agent_api_beta.php?source=test&user="+config.getUser()+"&pass="+config.getPassword()+"&function=get_campaign&json=1";`

**Comment by lrdgz** [comment]
//AVALIBLE FUNCTIONS TO API MOBILE
$api_allowed_functions_mobile = "get_campaign, change_ratio_campaign, get_list_campaign, activate_list_campaign, asign_list_campaign";

[non_agent_api_beta.zip](https://github.com/masterfermin02/ViciMobManager/files/2430758/non_agent_api_beta.zip)

download the file, and locate in your project to working.

**Comment by juanykty** [comment]
thanks
